# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hamzah Jamad
email: hamzahjamad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Programmer - Tinkerer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hamzahjamad.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: hamzahjamad
github_username:  hamzahjamad
facebook_username: hamzahjamad 

# Address information
address_street: "Jalan Istiadat, Kampung Likas"
address_city: Kota Kinabalu
address_state: Sabah
address_zip: 88400

# Build settings
markdown: kramdown
